spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/nnpdasema
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  main:
    allow-bean-definition-overriding: true
  mail:
    host: smtp-relay.brevo.com
    port: 587
    username: 7d0515001@smtp-brevo.com
    password: Vr2yzx9dUNWRZFX3
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          timeout: 5000
security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    expiration-time: 30000  # in millisecond = 1000ms = 1s
  user:
    name: admin
    password: admin

